version: '3.8'

services:
  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: ./Dockerfile
  #   image: chatvittis_whaticket-backend:1.0.0
  #   environment:
  #     - DB_HOST=postgres
  #     - DB_USER=user
  #     - DB_PASS=senha
  #     - DB_NAME=db_name
  #     - JWT_SECRET=3123123213123
  #     - JWT_REFRESH_SECRET=75756756756
  #     - BACKEND_URL=http://localhost:4000
  #     - FRONTEND_URL=http://localhost:3000
  #     - PROXY_PORT=
  #     - PORT=4000
  #     - REDIS_URI=redis://:123456@redis  # URI do Redis
  #     - NODE_ENV=production
  #     - CHROME_ARGS=--no-sandbox --disable-setuid-sandbox
  #     - REDIS_HOST=redis  # Host do Redis
  #     - REDIS_PORT=6379   # Porta do Redis
  #     - REDIS_PASSWORD=123456  # Senha do Redis, se estiver configurado
  #   ports:
  #     - 4000:4000
  #   volumes:
  #     - ./backend/public/:/usr/src/app/public/
  #     - ./backend/.wwebjs_auth/:/usr/src/app/.wwebjs_auth/
  #   depends_on:
  #     - postgres
  #     - redis

  # frontend:
  #   ports:
  #     - 3000:80
  #     - 3001:443
  #   build:
  #     context: ./frontend
  #     dockerfile: ./Dockerfile
  #   image: chatvittis_whaticket-frontend:1.0.0
  #   environment:
  #     - URL_BACKEND=backend:3000
  #     - REACT_APP_BACKEND_URL=http://localhost:4000/
  #     - FRONTEND_SERVER_NAME=frontend-server
  #     - BACKEND_SERVER_NAME=backend-server
  #   volumes:
  #     - ./frontend/src/:/usr/src/app/src/
  #     - ./frontend/public/:/usr/src/app/public/
  #   depends_on:
  #     - backend
  #     - postgres
  #     - redis

  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--requirepass", "123456"]

  postgres:
    image: postgres:latest
    container_name: postgres-server
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: db_name
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  redis-data:
    driver: local
  postgres-data:
    driver: local
